# Generated by Django 2.0.3 on 2018-03-20 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cushion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('pillow_color', models.SmallIntegerField(choices=[(0, 'niebieski'), (1, 'czerwony'), (2, 'zielony'), (3, 'czarny')])),
                ('kind', models.SmallIntegerField(choices=[(0, 'zwykła'), (1, 'włochata')])),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cushions', models.ManyToManyField(to='shop_app.Cushion')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('frame_color', models.SmallIntegerField(choices=[(0, 'żółty'), (1, 'niebieski'), (2, 'czerwony'), (3, 'zielony'), (4, 'brązowy')])),
                ('glass', models.SmallIntegerField(choices=[(0, 'matowe'), (1, 'przezroczyste')])),
                ('size', models.CharField(max_length=32)),
                ('passe_partout', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pictures',
            field=models.ManyToManyField(to='shop_app.Picture'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_app.User'),
        ),
    ]
