# Generated by Django 2.0.3 on 2018-03-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_auto_20180320_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
