# Generated by Django 2.0.3 on 2018-03-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_auto_20180321_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cushion',
            name='pillow_color',
            field=models.SmallIntegerField(choices=[(0, 'niebieski'), (1, 'czerwony'), (2, 'zielony'), (3, 'czarny'), (4, 'różowy'), (5, 'jasnozielony'), (6, 'granatowy')]),
        ),
        migrations.AlterField(
            model_name='picture',
            name='frame_color',
            field=models.SmallIntegerField(choices=[(-1, 'bez ramki'), (0, 'żółty'), (1, 'niebieski'), (2, 'czerwony'), (3, 'zielony'), (4, 'brązowy'), (5, 'czarny')]),
        ),
    ]
