# Generated by Django 2.0.3 on 2018-03-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_auto_20180322_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'Metryczki'), (1, 'Ślubne'), (2, 'Religijne'), (3, 'Przyroda'), (4, 'inne')]),
        ),
    ]
